version: "2.3"
services:
  jellyfin:
    image: jellyfin/jellyfin:unstable
    network_mode: "host"
    restart: "unless-stopped"
    runtime: nvidia
    environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
            - <PATH_TO_MEDIA>:/media:ro

